blank_issues_enabled: false
contact_links:
  - name: "💬 General Discussions"
    url: https://github.com/orgs/Novalabs-in/discussions
    about: Ask questions, share ideas, and connect with other builders in the Novalabs-in community.
